<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Returns list of posts by given page number.
     *
     * @param $receiverId
     *
     * @return array
     */
    public function getList($receiverId)
    {
        return [];
    }
}
