# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_provider:
        class: AppBundle\Security\AccessTokenUserProvider
        arguments:
            - "@doctrine.orm.entity_manager"

    app.authenticator:
        class:  AppBundle\Security\AccessTokenAuthenticator
        public: false

    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
